### ISSUE TITLE
oraclejdk7 is not supported anymore in Travis

### ISSUE THREAD

**Issue by rubensa** [mojohaus/webstart#60]
The Oracle Jdk7 is broken on container based trusty.

See [Trusty with oraclejdk7, ends with: ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle #7884](https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879)

While JAVA_HOME points to Jdk7, the actual executable java is set to Jdk8:

- java -version: 1.8.0_151
- JAVA_HOME: /usr/lib/jvm/java-7-oracle

Oracle Jdk8 and OpenJdk7 builds are still fine.

**Build log (exceprt):**

```bash
[…]
$ jdk_switcher use oraclejdk7
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle
[…]
$ mvn clean verify -B -e -V
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
[…]
```

**Travis.yml**

```yml
language: java
sudo: false
install: true

jdk: 
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - mvn clean verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
    except:
        - gh-pages

notifications:
email: true
```

**Workaround**

Remove Oracle Jdk7 builds.
